name: "Zimagi Commmand API Executor"
description: "GitHub Action for executing API based Zimagi commands"
inputs:
  command:
    description: "Full path of command (ex; module/list)"
    required: true
  options:
    description: "YAML/JSON encoded map of command options"
    required: false
    default: "{}"
  user:
    description: "Zimagi user name"
    required: false
    default: "admin"
  token:
    description: "Zimagi user token"
    required: true
  encryption_key:
    description: "Zimagi user encryption key"
    required: false
    default: ""
  host:
    description: "Zimagi Command API host"
    required: false
    default: "127.0.0.1"
  port:
    description: "Zimagi Command API port"
    required: false
    default: "5123"
  log_level:
    description: "Zimagi client log level"
    required: false
    default: "WARNING"
runs:
  using: docker
  image: Dockerfile
  args:
    - "${{ inputs.command }}"
    - '${{ inputs.options }}'
    - "--user=${{ inputs.user }}"
    - "--token=${{ inputs.token }}"
    - "--encryption-key=${{ inputs.encryption_key }}"
    - "--host=${{ inputs.host }}"
    - "--port=${{ inputs.port }}"
    - "--log-level=${{ inputs.log_level }}"
