version: '3.8'

services:
  action:
    network_mode: host
    image: zimagi/command
    build:
      context: .
      dockerfile: Dockerfile
    environment: {}
    env_file:
      - .env
    volumes:
      - ./action.py:/usr/local/bin/zimagi-action
    command:
      - "--host=127.0.0.1"
      - "--port=5123"
      - "--user=admin"
      - "--token=uy5c8xiahf93j2pl8s00e6nb32h87dn3"
      - "--name=module/get"
      - '--options={"module_key": "core"}'
