version: 2

jobs:
    deploy-docker-amd64-latest:
        resource_class: medium
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run:
                name: Deploy latest AMD Docker image
                command: ./.circleci/deploy_image.sh latest

    deploy-docker-arm64-latest:
        resource_class: arm.medium
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run:
                name: Deploy latest ARM Docker image
                command: ./.circleci/deploy_image.sh latest

    deploy-docker-latest:
        resource_class: medium
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run:
                name: Deploy latest Docker manifest
                command: ./.circleci/deploy_manifest.sh latest

    deploy-docker-amd64-version:
        resource_class: medium
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run:
                name: Deploy versioned AMD Docker image
                command: ./.circleci/deploy_image.sh

    deploy-docker-arm64-version:
        resource_class: arm.medium
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run:
                name: Deploy versioned ARM Docker image
                command: ./.circleci/deploy_image.sh

    deploy-docker-version:
        resource_class: medium
        machine:
            image: ubuntu-2204:current
        steps:
            - checkout
            - run:
                name: Deploy versioned Docker manifest
                command: ./.circleci/deploy_manifest.sh

workflows:
    version: 2
    deploy:
        jobs:
            - deploy-docker-amd64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
            - deploy-docker-arm64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
            - deploy-docker-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docker-amd64-latest
                    - deploy-docker-arm64-latest

            - deploy-docker-amd64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
            - deploy-docker-arm64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
            - deploy-docker-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docker-amd64-version
                    - deploy-docker-arm64-version
